-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2020-11-28 21:19:27 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE competitie (
    nume_competitie           VARCHAR2(30) NOT NULL,
    tip                       VARCHAR2(20) NOT NULL,
    numar_trofee_individuale  NUMBER(1),
    numar_trofee_colective    NUMBER(1) NOT NULL,
    numar_liga                VARCHAR2(10),
    grupe_nationale_id        NUMBER NOT NULL,
    id_liga                   NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE competitie
    ADD CHECK ( length(nume_competitie) > 8
                AND REGEXP_LIKE ( nume_competitie,
                                  '^[A-Za-z0-9 ]+$' ) );

ALTER TABLE competitie
    ADD CHECK ( tip IN ( 'Echipe de club', 'Echipe nationale' ) );

ALTER TABLE competitie ADD CONSTRAINT competitii_pk PRIMARY KEY ( nume_competitie );

CREATE TABLE directionare (
    palmares_palmares_id  NUMBER NOT NULL,
    trofee_trofee_id      NUMBER NOT NULL
)
LOGGING;

ALTER TABLE directionare ADD CONSTRAINT "palmares-trofee_PK" PRIMARY KEY ( palmares_palmares_id,
                                                                           trofee_trofee_id );

CREATE TABLE echipa_de_club (
    id_club             NUMBER(3) NOT NULL,
    nume_echipa         VARCHAR2(50) NOT NULL,
    oras                VARCHAR2(30) NOT NULL,
    numar_jucatori      NUMBER(2) NOT NULL,
    antrenor_principal  VARCHAR2(50) NOT NULL,
    id_liga             NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE echipa_de_club
    ADD CONSTRAINT nume_echipa_ck CHECK ( length(nume_echipa) > 8
                                          AND REGEXP_LIKE ( nume_echipa,
                                                            '^[A-Za-z0-9 ]+$' ) );

ALTER TABLE echipa_de_club
    ADD CONSTRAINT oras_ck CHECK ( length(oras) > 3
                                   AND REGEXP_LIKE ( oras,
                                                     '^[A-Za-z ]+$' ) );

ALTER TABLE echipa_de_club
    ADD CONSTRAINT numar_jucatori_ck CHECK ( numar_jucatori BETWEEN 11 AND 38 );

ALTER TABLE echipa_de_club
    ADD CONSTRAINT antrenor_principal_ck CHECK ( length(antrenor_principal) > 5
                                                 AND REGEXP_LIKE ( antrenor_principal,
                                                                   '^[A-Za-z ]+$' ) );

ALTER TABLE echipa_de_club ADD CONSTRAINT echipa_de_club_pk PRIMARY KEY ( id_club );

ALTER TABLE echipa_de_club ADD CONSTRAINT key_2 UNIQUE ( nume_echipa );

CREATE TABLE echipa_nationala (
    tara                      VARCHAR2(15) NOT NULL,
    numar_jucatori_convocati  NUMBER(2) NOT NULL,
    nume_selectioner          VARCHAR2(30) NOT NULL,
    grupe_nationale_id        NUMBER NOT NULL
)
LOGGING;

ALTER TABLE echipa_nationala
    ADD CONSTRAINT tara_ck CHECK ( length(tara) >= 3
                                   AND REGEXP_LIKE ( tara,
                                                     '^[A-Z]+[ A-Z]+$' ) );

ALTER TABLE echipa_nationala
    ADD CONSTRAINT numar_jucatori_convocati_ck CHECK ( numar_jucatori_convocati BETWEEN 11 AND 32 );

ALTER TABLE echipa_nationala
    ADD CONSTRAINT nume_selectioner_ck CHECK ( length(nume_selectioner) > 5
                                               AND REGEXP_LIKE ( nume_selectioner,
                                                                 '[A-Z]{1}[A-Za-z-]+ [A-Z]{1}[A-Za-z-]+$' ) );

ALTER TABLE echipa_nationala ADD CONSTRAINT echipa_nationala_pk PRIMARY KEY ( tara );

CREATE TABLE grupe_nationale (
    grupe_nationale_id      NUMBER NOT NULL,
    numar_echipe_nationale  NUMBER(2) NOT NULL,
    continent               VARCHAR2(20) NOT NULL
)
LOGGING;

ALTER TABLE grupe_nationale
    ADD CONSTRAINT numar_echipe_nationale_ck CHECK ( numar_echipe_nationale BETWEEN 0 AND 99 );

ALTER TABLE grupe_nationale
    ADD CONSTRAINT continent_ck CHECK ( continent IN ( 'Africa', 'America', 'Asia', 'Europa', 'Nu este nationala',
                                                       'Oceania_si_Australia' ) );

ALTER TABLE grupe_nationale ADD CONSTRAINT grupe_nationale_pk PRIMARY KEY ( grupe_nationale_id );

CREATE TABLE jucator_de_fotbal (
    id_player      NUMBER(3) NOT NULL,
    nume_jucator   VARCHAR2(100) NOT NULL,
    data_nasterii  DATE NOT NULL,
    inaltime       NUMBER(3) NOT NULL,
    greutate       NUMBER(3) NOT NULL,
    pozitie        VARCHAR2(9) NOT NULL,
    numar_goluri   NUMBER(3) NOT NULL,
    numar_meciuri  NUMBER(3) NOT NULL,
    numar_tricou   NUMBER(2),
    convocare      VARCHAR2(10) NOT NULL,
    retras         VARCHAR2(2) NOT NULL,
    atuu           VARCHAR2(15),
    id_club        NUMBER(3) NOT NULL,
    tara           VARCHAR2(15) NOT NULL,
    id_liga        NUMBER NOT NULL
)
LOGGING;

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT nume_jucator_ck CHECK ( length(nume_jucator) > 5
                                           AND REGEXP_LIKE ( nume_jucator,
                                                             '^[A-Za-z ]+$' ) );

ALTER TABLE jucator_de_fotbal ADD CONSTRAINT inaltime_ck CHECK ( inaltime > 150 );

ALTER TABLE jucator_de_fotbal ADD CONSTRAINT greutate_ck CHECK ( greutate > 50 );

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT pozitie_ck CHECK ( pozitie IN ( 'atacant', 'fundas', 'mijlocas', 'portar' ) );

ALTER TABLE jucator_de_fotbal ADD CONSTRAINT numar_goluri_ck CHECK ( numar_goluri >= 0 );

ALTER TABLE jucator_de_fotbal ADD CONSTRAINT numar_meciuri_ck CHECK ( numar_meciuri >= 0 );

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT numar_tricou_ck CHECK ( numar_tricou BETWEEN 1 AND 99 );

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT convocare_ck CHECK ( convocare IN ( 'convocat', 'neconvocat' ) );

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT retras_ck CHECK ( retras IN ( 'da', 'nu' ) );

ALTER TABLE jucator_de_fotbal ADD CONSTRAINT jucator_de_fotbal_pk PRIMARY KEY ( id_player );

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT key_2v2 UNIQUE ( nume_jucator,
                                    retras,
                                    convocare );

CREATE TABLE liga_de_fotbal (
    id_liga           NUMBER(2) NOT NULL,
    numar_liga        VARCHAR2(10) NOT NULL,
    numar_echipe      NUMBER(2) NOT NULL,
    numar_competitii  NUMBER(1) NOT NULL,
    tara              VARCHAR2(15) NOT NULL
)
LOGGING;

ALTER TABLE liga_de_fotbal
    ADD CONSTRAINT numar_liga_ck CHECK ( numar_liga IN ( 'Liga 1' ) );

ALTER TABLE liga_de_fotbal
    ADD CONSTRAINT numar_echipe_ck CHECK ( numar_echipe BETWEEN 16 AND 20 );

ALTER TABLE liga_de_fotbal
    ADD CONSTRAINT numar_competitii_ck CHECK ( numar_competitii BETWEEN 1 AND 3 );

ALTER TABLE liga_de_fotbal
    ADD CONSTRAINT "tara-liga_CK" CHECK ( length(tara) >= 3
                                          AND REGEXP_LIKE ( tara,
                                                            '^[A-Za-z]+[ A-Za-z]+$' ) );

ALTER TABLE liga_de_fotbal ADD CONSTRAINT liga_de_fotbal_pk PRIMARY KEY ( id_liga );

CREATE TABLE palmares (
    premii_individuale  NUMBER(2) NOT NULL,
    numar_cupe          NUMBER(2) NOT NULL,
    id_player           NUMBER(3) NOT NULL,
    palmares_id         NUMBER NOT NULL
)
LOGGING;

ALTER TABLE palmares ADD CONSTRAINT premii_individuale_ck CHECK ( premii_individuale >= 0 );

ALTER TABLE palmares ADD CONSTRAINT numar_cupe_ck CHECK ( numar_cupe >= 0 );

CREATE UNIQUE INDEX palmares__idx ON
    palmares (
        id_player
    ASC )
        LOGGING;

ALTER TABLE palmares ADD CONSTRAINT palmares_pk PRIMARY KEY ( palmares_id );

CREATE TABLE trofee (
    individuale      NUMBER(2) NOT NULL,
    colective        NUMBER(2) NOT NULL,
    nume_competitie  VARCHAR2(30) NOT NULL,
    trofee_id        NUMBER NOT NULL,
    anul_trofeului   NUMBER(4) NOT NULL
)
LOGGING;

ALTER TABLE trofee ADD CONSTRAINT individuale_ck CHECK ( individuale > 0 );

ALTER TABLE trofee ADD CONSTRAINT colective_ck CHECK ( colective > 0 );

ALTER TABLE trofee
    ADD CONSTRAINT nume_competitie_ck CHECK ( length(nume_competitie) > 8
                                              AND REGEXP_LIKE ( nume_competitie,
                                                                '[a-zA-Z0-9]' ) );

ALTER TABLE trofee
    ADD CONSTRAINT anul_trofeului_ck CHECK ( anul_trofeului BETWEEN 2000 AND 2020 );

ALTER TABLE trofee ADD CONSTRAINT trofee_pk PRIMARY KEY ( trofee_id );

ALTER TABLE directionare
    ADD CONSTRAINT directionare_trofee_fk FOREIGN KEY ( trofee_trofee_id )
        REFERENCES trofee ( trofee_id )
    NOT DEFERRABLE;

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT echipa_jucator_fk FOREIGN KEY ( id_club )
        REFERENCES echipa_de_club ( id_club )
    NOT DEFERRABLE;

ALTER TABLE competitie
    ADD CONSTRAINT "grupe-competitie_FK" FOREIGN KEY ( grupe_nationale_id )
        REFERENCES grupe_nationale ( grupe_nationale_id )
    NOT DEFERRABLE;

ALTER TABLE echipa_nationala
    ADD CONSTRAINT "Grupe-echipa_nat_FK" FOREIGN KEY ( grupe_nationale_id )
        REFERENCES grupe_nationale ( grupe_nationale_id )
    NOT DEFERRABLE;

ALTER TABLE palmares
    ADD CONSTRAINT "jucator-palmares_FK" FOREIGN KEY ( id_player )
        REFERENCES jucator_de_fotbal ( id_player )
    NOT DEFERRABLE;

ALTER TABLE competitie
    ADD CONSTRAINT "liga-competitie_FK" FOREIGN KEY ( id_liga )
        REFERENCES liga_de_fotbal ( id_liga )
    NOT DEFERRABLE;

ALTER TABLE echipa_de_club
    ADD CONSTRAINT "liga-echipa_FK" FOREIGN KEY ( id_liga )
        REFERENCES liga_de_fotbal ( id_liga )
    NOT DEFERRABLE;

ALTER TABLE jucator_de_fotbal
    ADD CONSTRAINT nationala_jucator_fk FOREIGN KEY ( tara )
        REFERENCES echipa_nationala ( tara )
    NOT DEFERRABLE;

ALTER TABLE directionare
    ADD CONSTRAINT "palmares-dir_FK" FOREIGN KEY ( palmares_palmares_id )
        REFERENCES palmares ( palmares_id )
    NOT DEFERRABLE;

ALTER TABLE trofee
    ADD CONSTRAINT "trofee-comp_FK" FOREIGN KEY ( nume_competitie )
        REFERENCES competitie ( nume_competitie )
    NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER Trg2_jucator_de_fotbal 
    BEFORE INSERT OR UPDATE ON jucator_de_fotbal 
    FOR EACH ROW 
BEGIN
	IF( :new.data_nasterii >= SYSDATE )
	THEN
		RAISE_APPLICATION_ERROR( -20001,
			'DATA INVALIDA: ' || TO_CHAR( :new.data_nasterii, 'DD.MM.YYYY') || ' trebuie sa fie mai mica decat data curenta.' );
	END IF;
END; 
/

CREATE SEQUENCE echipa_de_club_id_club_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER echipa_de_club_id_club_trg BEFORE
    INSERT ON echipa_de_club
    FOR EACH ROW
    WHEN ( new.id_club IS NULL )
BEGIN
    :new.id_club := echipa_de_club_id_club_seq.nextval;
END;
/

CREATE SEQUENCE grupe_nationale_grupe_national START WITH 1 MINVALUE 1 MAXVALUE 999 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER grupe_nationale_grupe_national BEFORE
    INSERT ON grupe_nationale
    FOR EACH ROW
    WHEN ( new.grupe_nationale_id IS NULL )
BEGIN
    :new.grupe_nationale_id := grupe_nationale_grupe_national.nextval;
END;
/

CREATE SEQUENCE jucator_de_fotbal_id_player START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER jucator_de_fotbal_id_player BEFORE
    INSERT ON jucator_de_fotbal
    FOR EACH ROW
    WHEN ( new.id_player IS NULL )
BEGIN
    :new.id_player := jucator_de_fotbal_id_player.nextval;
END;
/

CREATE SEQUENCE liga_de_fotbal_id_liga_seq START WITH 1 MINVALUE 1 MAXVALUE 99 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER liga_de_fotbal_id_liga_trg BEFORE
    INSERT ON liga_de_fotbal
    FOR EACH ROW
    WHEN ( new.id_liga IS NULL )
BEGIN
    :new.id_liga := liga_de_fotbal_id_liga_seq.nextval;
END;
/

CREATE SEQUENCE palmares_palmares_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER palmares_palmares_id_trg BEFORE
    INSERT ON palmares
    FOR EACH ROW
    WHEN ( new.palmares_id IS NULL )
BEGIN
    :new.palmares_id := palmares_palmares_id_seq.nextval;
END;
/

CREATE SEQUENCE trofee_trofee_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER trofee_trofee_id_trg BEFORE
    INSERT ON trofee
    FOR EACH ROW
    WHEN ( new.trofee_id IS NULL )
BEGIN
    :new.trofee_id := trofee_trofee_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             51
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
